# Generated by Django 2.2 on 2020-09-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realsecurity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='summary',
        ),
        migrations.AddField(
            model_name='feedback',
            name='comment',
            field=models.TextField(default='Enter your feedback', max_length=3000),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
